# permissions for end users to view customs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-viewer-role
rules:
- apiGroups:
  - batch.custom.com
  resources:
  - customs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.custom.com
  resources:
  - customs/status
  verbs:
  - get
